services:
  uptime-kuma:
    image: louislam/uptime-kuma:nightly2
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    # --- ĐÂY LÀ PHẦN BẠN CẦN ---
    extra_hosts:
      - "xxyz.com:10.2.30.5"
      - "api.internal:10.2.30.6" # Bạn có thể thêm nhiều dòng nếu muốn
    # ---------------------------
    volumes:
      - ./uptime-kuma-data:/app/data

# Khi bạn login lần đầu hệ thống sẽ yêu cầu bạn tạo tài khoản
